#spring.application.name=sensores

# Conexión a Neon PostgreSQL
#spring.datasource.url=jdbc:postgresql://ep-young-shape-anp1opq3-pooler.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require
#spring.datasource.username=neondb_owner
#spring.datasource.password=npg_WGAm3Jgv1OaH
#spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate - Actualiza las tablas automáticamente según tus entidades
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.show-sql=true

#spring.application.name=sensores

# Conexión a PostgreSQL (usa variable DB_URL o por defecto Neon)
#spring.datasource.url=${DB_URL:jdbc:postgresql://ep-young-shape-anp1opq3-pooler.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require}
#spring.datasource.username=${DB_USERNAME:neondb_owner}
#spring.datasource.password=${DB_PASSWORD:npg_WGAm3Jgv1OaH}
#spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.show-sql=true
#server.port=8081

spring.application.name=sensores

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/sensoresdb}
spring.datasource.username=${DB_USERNAME:admin}
spring.datasource.password=${DB_PASSWORD:admin123}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

server.port=${SERVER_PORT:8080}

#que se ejecute despues de hibernate
# 1. Forzamos a Hibernate a borrar y crear el esquema limpio en cada reinicio local
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 2. Diferimos la ejecución de data.sql para que corra estrictamente DESPUÉS de Hibernate
spring.jpa.defer-datasource-initialization=true

# 3. Ajustamos el modo de inicialización del script
#cambiar a always si se quiere insertar nuevos datos
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql

#para mqtt
mqtt.broker.url=${MQTT_BROKER_URL:tcp://localhost:1883}
mqtt.client.id=${MQTT_CLIENT_ID:spring-boot-sensores}
mqtt.topic.commands=${MQTT_COMMAND_TOPIC:sensores/commands}

app.security.jwt.secret-key=${JWT_SECRET:AgriSenseJwtSecretKeyLocalDebeTenerMasDe32Caracteres123}
app.security.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

JWT_SECRET: AgriSenseJwtSecretKeyLocalDebeTenerMasDe32Caracteres123
JWT_EXPIRATION_MS: 86400000